name: version

on:
  workflow_dispatch:

jobs:
  branch-protection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gh api -X PUT https://api.github.com/repos/basketry/.github/branches/main/protection --input branch.json
        with:
          GITHUB_TOKEN: ${{ github.token }}
