name: security

on:
  workflow_dispatch:

permissions: write-all

jobs:
  branch-protection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gh api -X PUT https://api.github.com/repos/basketry/.github/branches/main/protection --input branch.json
        env:
          GITHUB_TOKEN: ${{ github.token }}
